### ISSUE TITLE
Failed to compile using ESPHome 2024.12.4

### ISSUE THREAD

**Issue by och29** [dslatford/electriq_ac#4]
I wasn't able to get this working using the code as is on ESPHome 2024.12.4 and I'm also not a programmer but ChatGPT helped me to get something that would compile (not yet tested on the device). I've included it below in case anyone is able to review it, and will attempt to test it in the device at some point.

## Solution:
``` yaml
esphome:
  name: electriq-12000-ac
  friendly_name: INSERT YOUR OWN
  includes:
    - electriq_ac.h

esp8266:
  board: esp01_1m

logger:
  level: INFO

api:
  encryption:
    key: "INSERT YOUR OWN"

ota:
  - platform: esphome
    password: "INSERT YOUR OWN"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Electriq-12000-Ac"
    password: "INSERT YOUR OWN"

captive_portal:

uart:
  id: uart_bus
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600

climate:
  - platform: custom
    lambda: |-
      auto electriqac = new ElectriqAC(id(uart_bus));
      App.register_component(electriqac);
      return {electriqac};
    climates:
      - name: "Electriq 12000 AC"
        id: electriqac

globals:
  - id: overrun
    type: bool
    initial_value: "false"

script:
  - id: handle_overrun
    then:
      - globals.set:
          id: overrun
          value: "true"
      - logger.log: "Overrun fan mode, waiting 30s"
      - climate.control:
          id: electriqac
          mode: FAN_ONLY
      - delay: 30s
      - if:
          condition:
            lambda: |-
              auto *ac = static_cast<ElectriqAC*>(id(electriqac));
              return (ac->action == CLIMATE_ACTION_FAN);
          then:
            - logger.log: "Overrun finished, reverting to heat mode"
            - climate.control:
                id: electriqac
                mode: HEAT
      - if:
          condition:
            lambda: |-
              auto *ac = static_cast<ElectriqAC*>(id(electriqac));
              return ((ac->action == CLIMATE_ACTION_HEATING) && id(overrun));
          then:
            - logger.log: "Resetting overrun"
            - globals.set:
                id: overrun
                value: "false"

interval:
  - interval: 5s
    then:
      - lambda: |-
          auto *ac = static_cast<ElectriqAC*>(id(electriqac));
          if ((ac->action == CLIMATE_ACTION_IDLE) &&
              (ac->mode == CLIMATE_MODE_HEAT) &&
              !id(overrun)) {
            id(handle_overrun).execute();
          }
```

###   initial_error:
    description: >
      The configuration initially failed because the YAML referenced `id(electriqac)`
      in lambdas and automations, but no explicit ID was assigned to the custom climate component.
  abstract_binding_error:
 ###      description: >
      ESPHome’s automation system attempted to bind a function that took a parameter
      of the abstract type `Climate &` (which has pure virtual methods), leading to
      binding errors. This occurred when the lambda was not explicitly cast to the concrete type.
 ###    resolution_steps:
    - step: "Assigned an explicit ID (`id: electriqac`) to the custom climate component in the YAML."
    - step: "Modified lambda functions to cast the abstract parameter to the concrete type (`ElectriqAC`) using pointer casts."
    - step: "Moved the overrun automation logic out of the climate component's `on_state:` block into a top-level script combined with an interval trigger."
    - step: "Corrected pointer casting by removing the address-of operator so that `id(electriqac)` (already a pointer) is directly cast using `static_cast<ElectriqAC*>(id(electriqac))`."
###     final_outcome:
    description: >
      After applying these changes, the project compiled successfully without errors.
